version: '3'
services:
  nodejs:
    build:
      context: ./services/node
    tty: true
    volumes:
      - ./src:/app
    ports: 
      - "8080:8080"
      - "9229:9229"
    # command: /bin/bash -c "node --inspect=0.0.0.0 index.js"
    command: /bin/bash -c "node index.js"